"""rating_event_ladder_transition_fields

Revision ID: 476fb61b6b10
Revises: 20260222_0001
Create Date: 2026-02-22 19:18:26.815438
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '476fb61b6b10'
down_revision = '20260222_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratingevent', sa.Column('before_league', sa.String(), nullable=True))
    op.add_column('ratingevent', sa.Column('before_division', sa.String(), nullable=True))
    op.add_column('ratingevent', sa.Column('before_lp', sa.Integer(), nullable=True))
    op.add_column('ratingevent', sa.Column('after_league', sa.String(), nullable=True))
    op.add_column('ratingevent', sa.Column('after_division', sa.String(), nullable=True))
    op.add_column('ratingevent', sa.Column('after_lp', sa.Integer(), nullable=True))
    op.add_column('ratingevent', sa.Column('transition_type', sa.String(), nullable=False))
    op.add_column('ratingevent', sa.Column('major_promo_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratingevent', 'major_promo_name')
    op.drop_column('ratingevent', 'transition_type')
    op.drop_column('ratingevent', 'after_lp')
    op.drop_column('ratingevent', 'after_division')
    op.drop_column('ratingevent', 'after_league')
    op.drop_column('ratingevent', 'before_lp')
    op.drop_column('ratingevent', 'before_division')
    op.drop_column('ratingevent', 'before_league')
    # ### end Alembic commands ###
